import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@components";
import { peydaFont } from "@font";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${peydaFont.className}  antialiased container mx-auto border-t-4 border-t-cr2 py-5 px-3`}
      >
        <div className="flex flex-row gap-6 items-start">

          <Sidebar />

          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
